version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
  rails-app:
    build: ./rails-api
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails-api:/rails-app
    ports:
      - "3000:3000"
    depends_on:
      - db
